[package]
name = "strategy"
version = "0.1.0"
edition = "2021"

[lib]
name = "strategy"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
rust_decimal = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
